name: karmasu
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.3.4
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_gen: 5.10.0
  fl_chart: ^1.1.1
  pdf: ^3.10.7
  path_provider: ^2.1.2
  share_plus: ^12.0.1
  image: ^4.1.7
  printing: ^5.12.0
  http: ^1.1.0
  csv: ^6.0.0
  excel: ^4.0.6
  auto_size_text: ^3.0.0
  razorpay_flutter: ^1.3.7 
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.3.1
  audioplayers: ^6.5.1
  flutter_pdfview: ^1.4.1+1
  in_app_update: ^4.2.3
  url_launcher: ^6.2.4
  youtube_player_flutter: ^9.1.0
  youtube_player_iframe: ^5.2.0
  video_player: ^2.8.2
  chewie: ^1.7.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.15.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  vector_math: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/.env
    - assets/images/
    - assets/audio/
  generate: true
flutter_launcher_icons:
  android: "launcher_icon"  # Use launcher_icon for compatibility with Firebase/notifications
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 256

  macos:
    generate: true
    image_path: "assets/images/logo.png"
